# Generated by Django 3.1.7 on 2021-03-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerApp', '0002_auto_20210309_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
