# Generated by Django 3.1.7 on 2021-03-09 19:56

from django.db import migrations, models
import pokerApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerApp', '0003_auto_20210309_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default=None, upload_to=pokerApp.models.upload_image),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='matches',
            field=models.ManyToManyField(default=None, to='pokerApp.Match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
